FROM ubuntu:22.04

# Install miniconda
RUN apt-get update && apt-get install -y wget
RUN MINICONDA="Miniconda3-latest-Linux-x86_64.sh" && \
    wget --quiet https://repo.continuum.io/miniconda/$MINICONDA && \
    bash $MINICONDA -b -p /miniconda && \
    rm -f $MINICONDA
ENV PATH /miniconda/bin:$PATH

RUN conda install -c conda-forge -c michellab biosimspace
ENV SIRE_DONT_PHONEHOME 1

RUN conda install -c conda-forge gromacs

ADD conversion.py .
ADD Dockerfile_biosimspace .
