# See https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
name: 'Branch dispatch'
description: 'Check for the existence of a given fork & branch'
inputs:
  repository:
    description: 'The name of the repository only (without owner)'
    type: string
    required: true
  workflow_yml:
    description: 'The name of the workflow.yml file to be dispatched'
    type: string
    required: true
  sender_repo:
    description: 'The name of the initiating repository'
    type: string
    required: true
  sender_repo_owner:
    description: 'The name of the repository owner'
    type: string
    required: true
  sender_repo_ref:
    description: 'The name of the branch / ref'
    type: string
    required: true
  event_type:
    description: 'The name of the event type'
    type: string
    required: true
  commit_message:
    description: 'The commit message'
    type: string
    required: true
  mm_workflows_owner:
    description: 'The name of the mm-workflows owner'
    type: string
    required: true
  mm_workflows_ref:
    description: 'The name of the mm-workflows branch / ref'
    type: string
    required: true
  access_token:
    description: 'The token used for authentication'
    type: string
    required: true
outputs:
  response:
    description: 'The response text'
runs:
  using: 'node16'
  main: 'dist/index.js'
