#!/usr/bin/env cwl-runner
# This file was autogenerated using the Workflow Inference Compiler, version 0+unknown
# https://github.com/PolusAI/workflow-inference-compiler
steps:
- id: bbbc__step__1__bbbcdownload
  in:
    name:
      source: bbbc__step__1__bbbcdownload___name
    outDir:
      source: bbbc__step__1__bbbcdownload___outDir
  out:
  - outDir
  - outDir
  run: bbbc__step__1__bbbcdownload/bbbcdownload.cwl
- id: bbbc__step__2__subdirectory
  in:
    directory:
      source: bbbc__step__1__bbbcdownload/outDir
    glob_pattern:
      source: bbbc__step__2__subdirectory___glob_pattern
  out:
  - subdirectory
  - subdirectory
  run: bbbc__step__2__subdirectory/subdirectory.cwl
- id: bbbc__step__3__file-renaming
  in:
    filePattern:
      source: bbbc__step__3__file-renaming___filePattern
    inpDir:
      source: bbbc__step__2__subdirectory/subdirectory
    outDir:
      source: bbbc__step__3__file-renaming___outDir
    outFilePattern:
      source: bbbc__step__3__file-renaming___outFilePattern
  out:
  - outDir
  - outDir
  - preview_json
  run: bbbc__step__3__file-renaming/file-renaming.cwl
- id: bbbc__step__4__ome-converter
  in:
    fileExtension:
      source: bbbc__step__4__ome-converter___fileExtension
    filePattern:
      source: bbbc__step__4__ome-converter___filePattern
    inpDir:
      source: bbbc__step__3__file-renaming/outDir
    outDir:
      source: bbbc__step__4__ome-converter___outDir
  out:
  - outDir
  - outDir
  run: bbbc__step__4__ome-converter/ome-converter.cwl
- id: bbbc__step__5__montage
  in:
    filePattern:
      source: bbbc__step__5__montage___filePattern
    inpDir:
      source: bbbc__step__4__ome-converter/outDir
    layout:
      source: bbbc__step__5__montage___layout
    outDir:
      source: bbbc__step__5__montage___outDir
  out:
  - outDir
  - outDir
  - global_positions
  - preview_json
  run: bbbc__step__5__montage/montage.cwl
- id: bbbc__step__6__image_assembler
  in:
    imgPath:
      source: bbbc__step__4__ome-converter/outDir
    outDir:
      source: bbbc__step__6__image_assembler___outDir
    stitchPath:
      source: bbbc__step__5__montage/outDir
  out:
  - outDir
  - outDir
  - assembled_image
  - preview_json
  run: bbbc__step__6__image_assembler/image_assembler.cwl
- id: bbbc__step__7__precompute_slide
  in:
    imageType:
      source: bbbc__step__7__precompute_slide___imageType
    inpDir:
      source: bbbc__step__6__image_assembler/outDir
    outDir:
      source: bbbc__step__7__precompute_slide___outDir
    pyramidType:
      source: bbbc__step__7__precompute_slide___pyramidType
  run: bbbc__step__7__precompute_slide/precompute_slide.cwl
  out:
  - outDir
cwlVersion: v1.2
class: Workflow
$namespaces:
  edam: https://edamontology.org/
$schemas:
- https://raw.githubusercontent.com/edamontology/edamontology/master/EDAM_dev.owl
inputs:
  bbbc__step__1__bbbcdownload___name:
    type: string
    label: The name of the dataset(s) to be downloaded (separate the datasets with
      a comma. eg BBBC001,BBBC002,BBBC003)
    doc: The name of the dataset(s) to be downloaded (separate the datasets with a
      comma. eg BBBC001,BBBC002,BBBC003)
  bbbc__step__1__bbbcdownload___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
  bbbc__step__2__subdirectory___glob_pattern:
    type: string
  bbbc__step__3__file-renaming___filePattern:
    type: string
  bbbc__step__3__file-renaming___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
  bbbc__step__3__file-renaming___outFilePattern:
    type: string
  bbbc__step__4__ome-converter___fileExtension:
    type: string
    label: The file extension
    doc: The file extension
  bbbc__step__4__ome-converter___filePattern:
    type: string
    label: A filepattern, used to select data for conversion
    doc: A filepattern, used to select data for conversion
  bbbc__step__4__ome-converter___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
  bbbc__step__5__montage___filePattern:
    type: string
    label: Filename pattern used to parse data
    doc: Filename pattern used to parse data
  bbbc__step__5__montage___layout:
    type: string
    label: Specify montage organization
    doc: Specify montage organization
  bbbc__step__5__montage___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
  bbbc__step__6__image_assembler___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
  bbbc__step__7__precompute_slide___imageType:
    type: string
    label: Image is either Segmentation or Image
    doc: Image is either Segmentation or Image
  bbbc__step__7__precompute_slide___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
  bbbc__step__7__precompute_slide___pyramidType:
    type: string
    label: Build a DeepZoom, Neuroglancer, Zarr pyramid
    doc: Build a DeepZoom, Neuroglancer, Zarr pyramid
outputs:
  bbbc__step__1__bbbcdownload___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
    outputSource: bbbc__step__1__bbbcdownload/outDir
  bbbc__step__2__subdirectory___subdirectory:
    type: Directory
    outputSource: bbbc__step__2__subdirectory/subdirectory
  bbbc__step__3__file-renaming___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
    outputSource: bbbc__step__3__file-renaming/outDir
  bbbc__step__3__file-renaming___preview_json:
    type:
    - 'null'
    - File
    format: edam:format_3464
    label: JSON file describing what the outputs should be
    doc: JSON file describing what the outputs should be
    outputSource: bbbc__step__3__file-renaming/preview_json
  bbbc__step__4__ome-converter___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
    outputSource: bbbc__step__4__ome-converter/outDir
  bbbc__step__5__montage___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
    outputSource: bbbc__step__5__montage/outDir
  bbbc__step__5__montage___global_positions:
    type:
    - 'null'
    - File
    label: The "stitching vector", i.e. the positions of the individual images in
      the montage
    doc: The "stitching vector", i.e. the positions of the individual images in the
      montage
    outputSource: bbbc__step__5__montage/global_positions
  bbbc__step__5__montage___preview_json:
    type:
    - 'null'
    - File
    format: edam:format_3464
    label: JSON file describing what the outputs should be
    doc: JSON file describing what the outputs should be
    outputSource: bbbc__step__5__montage/preview_json
  bbbc__step__6__image_assembler___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
    outputSource: bbbc__step__6__image_assembler/outDir
  bbbc__step__6__image_assembler___assembled_image:
    type:
    - 'null'
    - File
    format: edam:format_3727
    label: The assembled montage image
    doc: JSON file with outputs
    outputSource: bbbc__step__6__image_assembler/assembled_image
  bbbc__step__6__image_assembler___preview_json:
    type:
    - 'null'
    - File
    format: edam:format_3464
    label: JSON file with outputs
    doc: JSON file with outputs
    outputSource: bbbc__step__6__image_assembler/preview_json
  bbbc__step__7__precompute_slide___outDir:
    type: Directory
    label: Output collection
    doc: Output collection
    outputSource: bbbc__step__7__precompute_slide/outDir
