FROM ubuntu:22.04 as download

# Install miniconda
RUN apt-get update && apt-get install -y wget
RUN MINICONDA="Miniconda3-latest-Linux-x86_64.sh" && \
    wget --quiet https://repo.continuum.io/miniconda/$MINICONDA && \
    bash $MINICONDA -b -p /miniconda && \
    rm -f $MINICONDA
ENV PATH /miniconda/bin:$PATH

RUN conda install -c conda-forge wget libarchive
# bsdtar is installed with libarchive; see download_data.sh

ADD Dockerfile_data .
ADD download_data.sh .

RUN ./download_data.sh

# Now copy everything into a minimal alpine linux distro.
# Ideally we would like to use FROM scratch, but we need the `cp` command.
FROM alpine as data

COPY --from=download *.sdf ./
COPY --from=download *.xlsx ./
COPY --from=download Dockerfile_data ./
COPY --from=download download_data.sh ./