# IMPORTANT: Use .. for the Build Context https://docs.docker.com/build/building/context/
# i.e. `sudo docker build ... -f Dockerfile ..`
FROM debian:stable-slim

# Install conda / mamba
RUN apt-get update -y && apt-get install -y wget

RUN CONDA="Miniforge3-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /miniforge && \
    rm -f $CONDA
ENV PATH /miniforge/bin:$PATH

# Install sophios first
RUN apt-get install -y git

COPY . /workflow-inference-compiler
WORKDIR /workflow-inference-compiler

# This is a Docker image; we don't necessarily need to additionally isolate
# wic within a conda environment. Let's just install it globally!
RUN mamba env update --name base --file install/system_deps.yml
RUN pip install -e ".[all]"

RUN mamba clean --all --yes
RUN pip cache purge
RUN apt-get clean

# Then run the sophios REST API through port 3000
EXPOSE 3000

CMD ["uvicorn", "sophios.api.http.restapi:app", "--host", "0.0.0.0", "--port", "3000"]

ADD docker/Dockerfile_debian_rest .
