# IMPORTANT: Use .. for the Build Context https://docs.docker.com/build/building/context/
# i.e. `sudo docker build ... -f Dockerfile ..`
FROM debian:stable-slim

# Install conda / mamba
RUN apt-get update && apt-get install -y wget

# NOTE: Use regular Mambaforge, NOT Mambaforge-pypy3 because uvicorn is incompatible with pypy.
# See https://github.com/encode/uvicorn/blob/28fc4bdb77d1bd2f541ca7e0b3bd6fe1155e162f/pyproject.toml#L42
# (This is NOT the same thing as using Mambaforge-pypy3 and simply not installing pypy!)
RUN CONDA="Mambaforge-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /mambaforge && \
    rm -f $CONDA
ENV PATH /mambaforge/bin:$PATH

# IMPORTANT: The system_deps.yml step can take a LONG time
# (~2 hours with conda, ~60 seconds with mamba...)
# so we *really* want to cache it. Since docker uses the hash of
# ALL of the files, directories, etc. we ONLY want to copy
# system_deps.yml now. Then, we can copy everything else.
# See https://stackoverflow.com/questions/48551953/
COPY install/system_deps.yml /workflow-inference-compiler/install/system_deps.yml
RUN mamba env update --name base --file /workflow-inference-compiler/install/system_deps.yml

# NOW we can copy everything else.
COPY . /workflow-inference-compiler
WORKDIR /workflow-inference-compiler

# Install specific versions of some dependencies to match cyto-explorer.
# See https://github.com/PolusAI/cyto-explorer/blob/main/packages/vaex-api/requirements.txt
# (Otherwise, may cause auth issues.)

RUN mamba install -c conda-forge "uvicorn<0.16.0" "fastapi==0.73.0" "requests==2.26.0"

# Install wic
RUN apt-get install -y git
RUN pip install -e ".[restapi, runners_src]"

# Minimize image
RUN mamba clean --all --yes
RUN pip cache purge
RUN apt-get clean

EXPOSE 3000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "3000"]

ADD docker/Dockerfile_debian_REST_API .