#!/bin/bash -e
cd ../..

if [ -d "mm-workflows" ]
then
    echo "Directory mm-workflows already exists."
    echo "Please install mm-workflows manually."
    exit 1
else
    git clone https://github.com/PolusAI/mm-workflows.git
    cd mm-workflows
    pip install -e ".[all]"
    # Also run mm-workflows command to generate
    # autogenerated/schemas/config_schemas.json
    mm-workflows
fi
