#!/bin/bash -e
cd ../..

if [ -d "mm-workflows" ]
then
    echo "Directory mm-workflows already exists."
    echo "Please install mm-workflows manually."
    exit 1
else
    git clone https://github.com/PolusAI/mm-workflows.git
    cd mm-workflows
    # NOTE: Use ".[test]" instead of ".[all]"
    # We do not want or need to install the workflow_deps extra.
    # (Many of the packages conflict with pypy.)
    pip install -e ".[test]"
    # Also run mm-workflows command to generate
    # autogenerated/schemas/config_schemas.json
    mm-workflows --generate_schemas
fi
