FROM ubuntu:22.04

# Install miniconda
RUN apt-get update && apt-get install -y wget
RUN MINICONDA="Miniconda3-latest-Linux-x86_64.sh" && \
    wget --quiet https://repo.continuum.io/miniconda/$MINICONDA && \
    bash $MINICONDA -b -p /miniconda && \
    rm -f $MINICONDA
ENV PATH /miniconda/bin:$PATH

RUN conda install -c conda-forge pandas

ADD Dockerfile_PDBbind_refined .
ADD generate_pdbbind_complex.py .
ADD PDBbind_v2020_refined.tar.gz .
