name: Build and Test Wheel

on:
  pull_request: 
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install sophios 🔧
        run: |
          pip install .[test]
      - name: Test with pytest
        run: |
          python -m pytest -k test_cwl_docker_extract
          python -m pytest -m "not skip_pypi_ci" -vv

      - name: Build sophios
        run: |
          python -m pip install twine build
          python -m build --wheel
          python -m build --sdist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
            name: sophios-wheels
            path: dist/*
            retention-days: 1
